version: "3.9"
services:
  acme:
    image: pierre42100/acme-responder
    environment:
    - DOMAIN_URI=https://secure
    - STORAGE_PATH=/storage
    volumes:
    - ./storage:/storage
  
  secure:
    image: pierre42100/acme-eval-tlsreverseproxy

  client:
    image: pierre42100/acme-eval-client
    entrypoint: ["bash", "-c", "mkdir /storage; cd /storage; python3 -m http.server 80"]

